In [ ]:



class Solution:

  def local_alignment(self, sequence_A: str, sequence_B:str,substitution: dict, gap: int ):
    import pandas as pd
    import numpy as np
    df=pd.DataFrame(dict)
    print('the substitution matrix')
    print(df)

    print()
    print()
    print('the matrix for the given sequence')
    substitution_matrix=df.to_numpy()

    a=len(sequence_A)
    b=len(sequence_B)


    est_matrix = np.zeros((a + 1, b + 1))
    pointerTable = np.zeros((a+1, b+1), dtype=int)

    r,c=(est_matrix.shape)

    for row in range(r):
      for column in range(c):
        if row==0:
          est_matrix[row][column]=column*0

        elif column==0:
          est_matrix[row][column]=row*0
    for i in range(len(sequence_A)):
      for j in range(len(sequence_B)):
          dia=est_matrix[i][j]+dict[sequence_A[i]][sequence_B[j]]
          top=est_matrix[i+1][j]+gap
          lft=est_matrix[i][j+1]+gap
          if max(dia,lft,top)>0:
            est_matrix[i+1][j+1]=max(dia,lft,top)
          else :
            est_matrix[i+1][j+1]=0
          if(est_matrix[i+1][j+1] == 0):
                pointerTable[i+1][j+1] = 4
          elif (est_matrix[i+1][j+1] == dia):
                pointerTable[i+1][j+1] = 3
          elif (est_matrix[i+1][j+1] == top):
                pointerTable[i+1][j+1] = 2
          elif (est_matrix[i+1][j+1] == lft):
                pointerTable[i+1][j+1] = 1
    print(est_matrix)

    alSeq1 = ""
    alSeq2 = ""
    rx = []
    ry = []
    i, j = np.unravel_index(est_matrix.argmax(), est_matrix.shape)
    score = est_matrix.max()
    while i > 0 and j > 0:
        if pointerTable[i][j] == 4:
            break
        if pointerTable[i][j] == 3:
            rx.append(sequence_A[i-1])
            ry.append(sequence_B[j-1])
            i -= 1
            j -= 1
        elif pointerTable[i][j] == 1:
            rx.append('-')
            ry.append(sequence_B[j-1])
            j -= 1
        elif pointerTable[i][j] == 2:
            rx.append(sequence_A[i-1])
            ry.append('-')
            i -= 1


  # Reverse the strings.
    rx = ''.join(rx)[::-1]
    ry = ''.join(ry)[::-1]

    print('\n'.join([rx, ry]))


In [ ]:
WS=Solution()
dict={'a': {'a': 1, 'c': -1, 't': -1,'g':-1}, 'c': {'a': -1, 'c': 1, 't': -1,'g':-1}, 't': {'a': -1, 'c': -1, 't': 1,'g':-1},'g': {'a': -1, 'c': -1, 't': -1,'g':1}}
WS.local_alignment('gata','ctac',dict,-2)

the substitution matrix
   a  c  t  g
a  1 -1 -1 -1
c -1  1 -1 -1
t -1 -1  1 -1
g -1 -1 -1  1


the matrix for the given sequence
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 2. 0.]]
ta
ta
